spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpaceApps
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy